INSERT INTO NEXTI_AUSENCIAS_ALTERDATA(NUMEMP, TIPCOL, NUMCAD, ABSENCESITUATIONEXTERNALID, FINISHDATETIME, STARTDATETIME, IDEXTERNO, TIPO, SITUACAO)
SELECT
    NEXTI_COLABORADOR.NUMEMP,
    NEXTI_COLABORADOR.TIPCOL,
    NEXTI_COLABORADOR.NUMCAD,
    15671 AS ABSENCESITUATIONEXTERNALID,
    NULL as FINISHDATETIME,
    NEXTI_COLABORADOR.DATADEM AS STARTDATETIME,
    CONCAT(
        'DM-', NEXTI_COLABORADOR.NUMEMP, '-', NEXTI_COLABORADOR.NUMCAD, '-',
        DATE_FORMAT(NEXTI_COLABORADOR.DATADEM, '%Y-%m-%d')
    ) AS IDEXTERNO,
    0 AS TIPO,
    0 AS SITUACAO
FROM NEXTI_COLABORADOR
WHERE NEXTI_COLABORADOR.DATADEM IS NOT NULL
AND NEXTI_COLABORADOR.SITFUN = 3
AND NEXTI_COLABORADOR.TIPO <> 3
AND NOT EXISTS(
    SELECT
        1
    FROM NEXTI_AUSENCIAS_ALTERDATA
    WHERE IDEXTERNO = CONCAT(
        'DM-',
        NEXTI_COLABORADOR.NUMEMP, '-', NEXTI_COLABORADOR.NUMCAD, '-',
        DATE_FORMAT(NEXTI_COLABORADOR.DATADEM, '%Y-%m-%d')
    )
)